// fixtures/react-app/src/components/LoginForm.tsx
'use client';

import { useState } from 'react';

export default function LoginForm() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    // login logic
  };

  return (
    <form onSubmit={handleSubmit}>
      <label htmlFor="email">Email address</label>
      <input
        id="email"
        type="email"
        value={email}
        onChange={(e) => setEmail(e.target.value)}
        placeholder="you@example.com"
      />

      <label htmlFor="password">Password</label>
      <input
        id="password"
        type="password"
        value={password}
        onChange={(e) => setPassword(e.target.value)}
        placeholder="Enter password"
      />

      <button type="submit">Sign in</button>

      <a href="/forgot-password">Forgot password?</a>
    </form>
  );
}

// fixtures/vue-app/src/components/LoginForm.vue
<template>
  <form @submit.prevent="handleLogin">
    <input placeholder="Email" @input="validateEmail" />
    <input type="password" placeholder="Password" />
    <button>Log In</button>
    <a href="/forgot-password">Forgot password?</a>
  </form>
</template>

<script setup lang="ts">
function handleLogin() {}
function validateEmail() {}
</script>
